language: swift
os: osx
osx_image: xcode10.2

matrix:
  include:
#  - env: BUILD_ENV=arm64 SCHEME=ElastosDIDSDK BUILD_TYPE=Debug SDK=iphoneos12.2

  - env: BUILD_ENV=x64 SCHEME=ElastosDIDSDK BUILD_TYPE=Debug SDK=iphonesimulator12.2

install:
  #- brew install appledoc
  - .script/download_libs.sh ${BUILD_ENV}

script:
  - xcodebuild -showsdks
  - xcodebuild -list -project ElastosDIDSDK.xcodeproj
  - xcodebuild -scheme ${SCHEME} -configuration ${BUILD_TYPE} -sdk ${SDK} CODE_SIGNING_REQUIRED=NO
  #- ./docs.sh
